name: Check SQLite version

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  check-sqlite-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check SQLite version
        run: |
          export CURRENT_SQLITE_FORMULA_PATH=$GITHUB_WORKSPACE/Formula/db4ssqlitefts@5.rb
          export CURRENT_VERSION=$(grep -o 'version "\S*"' ${CURRENT_SQLITE_FORMULA_PATH} | awk '{print $2}' | tr -d '"')
          export LATEST_VERSION=$(curl -s https://sqlite.org/download.html | awk '/<!--/,/-->/ {print}' | grep 'sqlite-autoconf' | cut -d ',' -f 2)
          
          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
              echo IS_SQLITE_UPDATED=0 >> $GITHUB_ENV
          else
              echo IS_SQLITE_UPDATED=1 >> $GITHUB_ENV
              echo CURRENT_VERSION=$CURRENT_VERSION >> $GITHUB_ENV
              echo LATEST_VERSION=$LATEST_VERSION >> $GITHUB_ENV
          fi

      - if: env.IS_SQLITE_UPDATED == 1
        name: Generate issue
        env:
          CURRENT_VERSION: ${{ env.CURRENT_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_VERSION: ${{ env.LATEST_VERSION }}
          IS_SQLITE_UPDATED: ${{ env.IS_SQLITE_UPDATED }}
        run: |
          gh issue create \
            --assignee ${{ vars.ASSIGNEES }} \
            --body "SQLite has been updated from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}." \
            --title "SQLite has been updated (v${{ env.LATEST_VERSION }})" \
            --repo ${{ github.repository }}