name: brew livecheck

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  check:
    name: livecheck
    runs-on: macos-15
    steps:
      - run: brew tap $GITHUB_REPOSITORY

      - name: Run the script
        env:
          ASSIGNEES: ${{ vars.ASSIGNEES }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 "$(brew --prefix)/Library/Taps/${GITHUB_REPOSITORY}/.github/scripts/check-update.py"
